[package]
name = "surfgen"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.6"
noise = { version = "0.9.0", features = ["image"] }
num-traits = "0.2.19"
vek = { version = "0.17.1", features = ["image"] }

[profile.dev]
opt-level = 2
